### ISSUE TITLE
Revise the version of Pandas being targeted

### ISSUE THREAD

**Issue by TinyMarsh** [EnergySystemsModellingLab/MUSE_OS#120]
While experimenting with extending the CI workflow (#119) to test on a matrix of python versions (3.8 - 3.11) and platforms (Linux, Windows and MacOS), tests failed for Python versions 3.10 and 3.11 on all platforms.

The cause of failure in each of these combinations was the targeting of `pandas<=1.3`. As per [the documentation](https://pandas.pydata.org/pandas-docs/version/1.3/getting_started/install.html#python-version-support), Pandas 1.3 does not support Python versions 3.10+. The minimum version of Pandas which supports up to Python 3.11 is [Pandas 1.5](https://pandas.pydata.org/pandas-docs/version/1.5/getting_started/install.html#python-version-support).

Suggest investigating if MUSE's dependency of `pandas<=1.3` is still relevant and, is possible, switch to targeting `pandas>=1.5`.

**Comment by sgiarols** [comment]
Thanks. I often regret that we moved to xarray, rather than just sticking to pandas, as xarray constantly undergoes massive updates. I think we need the tool should be sustained in the long-term and that an upgrade to the newest packages seems crucial at this stage. I would leave to @ahawkes final considerations, as the refactoring time, if we decide to go for it, may require a conversation on the engagement plans.

**Comment by dalonsoa** [comment]
I think `xarray` is the right tool for the job, but it is true that we picked it when it was in a very early state of development and it was not stable. That was possibly an error, indeed. The update in 2022.6.0 has annoyed a lot of people, but I think it has made the tool more mature and things should be more mature from now on.

Thinking in the future, I think it is important not to kick the can down the road and when incompatibilities arise with any new version of any package, we fix them rather than pinning to an older version because that only makes the tool to accumulate technical debt until it explodes.

Anyway, let's thing about it and maybe we can have a chat about how to best proceed.

**Comment by dalonsoa** [comment]
I've already started to work on this. Fixed a couple of issues, but I'm stuck in another. I've posted a question in StackOverflow in case someone can point me in the right direction: https://stackoverflow.com/questions/76471238/why-i-cannot-add-a-dataarray-to-an-existing-dataset-with-a-multiindex

**Comment by dalonsoa** [comment]
Following on this, the minimum working example meant to reproduce our problem that I described in https://github.com/pydata/xarray/issues/7921 is working fine. It is unclear why it is not working for us. I suspect the culprit is in the timeslices, which are a really complex structure and might have been created in a way not fully compatible with the current way of doing things. I'm trying to get to a minimum working example that works with our structure.
