### ISSUE TITLE
[BUG] A single standalone technology cannot produce more than one commodity

### ISSUE THREAD

**Issue by AAQ2019** [EnergySystemsModellingLab/MUSE_OS#249]
An example of one technology with multiple output commodities is Oil Refinery which takes in Crude Oil and produces LPG, DSL, and GASOLINE.

It is possible to assign more than one output commodity in CommOut.csv, however, in Technodata.csv there is only one EndUse per technology. This will not fit for the other output commodities. So, if the same technology is replicated in Technodata.csv for the same techno-economic parameters for the same timeframe while changing EndUse commodity to fit for all output commodities, this will still not work and will creates the following error:
 
ValueError: cannot convert a DataFrame with a non-unique MultiIndex into xarray

**Comment by sgiarols** [comment]
Replicating technologies for different enduses in the technodata is not the correct approach, as evidenced by the ValueError.
The technodata EndUse is not meant to be replicated in the way described because it is just used at the moment of screening / filtering across technologies in terms of their main product. It is thus used as an agent filter.
The method to have multiple outputs is just via the standard CommOUT.csv.
I hope this clarifes.
