### ISSUE TITLE
[BUG] Release workflow is failing to publish to PyPI

### ISSUE THREAD

**Issue by alexdewar** [EnergySystemsModellingLab/MUSE_OS#443]
Currently the `publish.yml` workflow [is failing to publish to PyPI](https://github.com/EnergySystemsModellingLab/MUSE_OS/actions/runs/10158629866). (In case the CI logs disappear, I've pasted the error message below.)

This *might* have been broken by #231, as this changed the name of the workflow file, and you have to specify in your PyPI user settings which workflows are allowed to publish packages (as a security measure). This PR was merged after our last release. Alternatively, it may be because the name of the GitHub org has been changed.

Does anyone know who has access to the PyPI account for MUSE? @ahawkes? @dalonsoa?

----------------------------

Trusted publishing exchange failure:

Token request failed: the server refused the request for the following reasons:

invalid-publisher: valid token, but no corresponding publisher (All lookup strategies exhausted)
This generally indicates a trusted publisher configuration error, but could
also indicate an internal error on GitHub or PyPI's part.

The claims rendered below are for debugging purposes only. You should not
use them to configure a trusted publisher unless they already match your expectations.

If a claim is not present in the claim set, then it is rendered as MISSING.

sub: repo:EnergySystemsModellingLab/MUSE_OS:ref:refs/tags/v1.2.0rc1
repository: EnergySystemsModellingLab/MUSE_OS
repository_owner: EnergySystemsModellingLab
repository_owner_id: 11629231
job_workflow_ref: EnergySystemsModellingLab/MUSE_OS/.github/workflows/publish.yml@refs/tags/v1.2.0rc1
ref: refs/tags/v1.2.0rc1
See https://docs.pypi.org/trusted-publishers/troubleshooting/ for more help.

You're seeing this because the action wasn't given the inputs needed to
perform password-based or token-based authentication. If you intended to
perform one of those authentication methods instead of trusted
publishing, then you should double-check your secret configuration and variable
names.

Read more about trusted publishers at https://docs.pypi.org/trusted-publishers/

Read more about how this action uses trusted publishers at
https://github.com/marketplace/actions/pypi-publish#trusted-publishing

**Comment by ahawkes** [comment]
I do not know who has this access…
A
________________________________
From: Alex Dewar ***@***.***>
Sent: Monday, August 5, 2024 6:04:49 PM
To: EnergySystemsModellingLab/MUSE_OS ***@***.***>
Cc: Hawkes, Adam D ***@***.***>; Mention ***@***.***>
Subject: [EnergySystemsModellingLab/MUSE_OS] [BUG] Release workflow is failing to publish to PyPI (Issue #443)


This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



Currently the publish.yml workflow is failing to publish to PyPI<https://github.com/EnergySystemsModellingLab/MUSE_OS/actions/runs/10158629866>. (In case the CI logs disappear, I've pasted the error message below.)

This might have been broken by #231<https://github.com/EnergySystemsModellingLab/MUSE_OS/pull/231>, as this changed the name of the workflow file, and you have to specify in your PyPI user settings which workflows are allowed to publish packages (as a security measure). This PR was merged after our last release. Alternatively, it may be because the name of the GitHub org has been changed.

Does anyone know who has access to the PyPI account for MUSE? @ahawkes<https://github.com/ahawkes>? @dalonsoa<https://github.com/dalonsoa>?

________________________________

Trusted publishing exchange failure:

Token request failed: the server refused the request for the following reasons:

invalid-publisher: valid token, but no corresponding publisher (All lookup strategies exhausted)
This generally indicates a trusted publisher configuration error, but could
also indicate an internal error on GitHub or PyPI's part.

The claims rendered below are for debugging purposes only. You should not
use them to configure a trusted publisher unless they already match your expectations.

If a claim is not present in the claim set, then it is rendered as MISSING.

sub: repo:EnergySystemsModellingLab/MUSE_OS:ref:refs/tags/v1.2.0rc1
repository: EnergySystemsModellingLab/MUSE_OS
repository_owner: EnergySystemsModellingLab
repository_owner_id: 11629231
job_workflow_ref: ***@***.***/tags/v1.2.0rc1
ref: refs/tags/v1.2.0rc1
See https://docs.pypi.org/trusted-publishers/troubleshooting/ for more help.

You're seeing this because the action wasn't given the inputs needed to
perform password-based or token-based authentication. If you intended to
perform one of those authentication methods instead of trusted
publishing, then you should double-check your secret configuration and variable
names.

Read more about trusted publishers at https://docs.pypi.org/trusted-publishers/

Read more about how this action uses trusted publishers at
https://github.com/marketplace/actions/pypi-publish#trusted-publishing

**Comment by alexdewar** [comment]
No worries. I was wondering if it might be @sgiarols? But it's probably @dalonsoa. I'll ask him when he gets back.

**Comment by alexdewar** [comment]
Just a reminder that we should do #224 once we've fixed this!

**Comment by ahawkes** [comment]
Thanks – I have created the accounts in pypi and test.pypi – username is ahawkes.

**Comment by dalonsoa** [comment]
@ahawkes , I've invited to be owner of both services. You will need to accept the invitation. I've also transfer the ownership from my account to `imperial-rse-team`.

**Comment by alexdewar** [comment]
> Anyway, trying to make a release now should work... I think :)

It has indeed! Thanks :smile:

**Comment by dalonsoa** [comment]
The previous RC also went through 7h ago, aparently...
<img width="577" alt="image" src="https://github.com/user-attachments/assets/456e4c76-f852-4ae7-8d24-3c951922fe12">

**Comment by alexdewar** [comment]
Hmm... not sure what happened there :shrug:
